try{
console.log(erro) } catch(err) {
    console.log("Deu pau")
}

try {
    // throw new Error('Mensagem de erro')
} catch {
    console.log('Erro desconhecido');
}